### ISSUE TITLE
Personal contact 4 teh haxmaking xoxo

### ISSUE THREAD

**Issue by ericek111** [owerosu/linux-csgo-external#11]
Dear Mr. owerosu,
would you be so kind and allow me to contact you using some insta-messaging service, please? I'd like to discuss some 1337 hax. Deez forums and stuff are not really good for that. It feels more like e-mails...

Thanks a lot, fellow contributor!

**Comment by owerosu** [comment]
Owerosu on skype

**Comment by ericek111** [comment]
I've added you there few weeks ago, but you are either sneaky stalking invisibler, or offline (might be the reason why there's a little yellow warning triangle next to the message I've just sent you - interesting).

**Comment by owerosu** [comment]
I'm spamming you right now.

**Comment by ericek111** [comment]
wtf, shit doesn't work then. My Skype's erikbobrik.

**Comment by owerosu** [comment]
web skype rules I guess

**Comment by ericek111** [comment]
web.skype.com worked. broken MS stuff... sort your expensive shit out plz.
