### ISSUE TITLE
I have 1 question?

### ISSUE THREAD

**Issue by Elpapirico96** [owerosu/linux-csgo-external#2]
You will keep this updated?, as far the community knows, the Aimtux injector got detected but the cheat doesn't, so this have a different way to inject?, thanks

**Comment by jalius** [comment]
this is not an internal cheat. it stays updated because of the memory signatures. i think owerosu just uploaded it for his friend, judging by the commits, so no one knows if he will keep it updated.

**Comment by R3lax0** [comment]
dude u have the source code and if there will be any kind of update that breaks the sigs, just update them.
