### ISSUE TITLE
trigger bot doesn't work anymore

### ISSUE THREAD

**Issue by olaulau** [owerosu/linux-csgo-external#3]
I think all is in the title :
for me, toggle key wasn't working, so I changed should_trigger to true.
since last CS-GO update, it doesn't trigger anymore.

**Comment by owerosu** [comment]
Yep, we'll add sigscan very soon.
Last offset:
client->client_start)+0x62E9144

**Comment by owerosu** [comment]
Added a sig for attack in the triggerbot branch, should fix the issue
