### ISSUE TITLE
no flash stopped working

### ISSUE THREAD

**Issue by olaulau** [owerosu/linux-csgo-external#4]

**Comment by owerosu** [comment]
Are you sure ? Everything is fine on my side. It supposed to reduced the flash, not totally remove it.

**Comment by olaulau** [comment]
yes i know. It worked few days ago, yesturday it seemed not to work. I'll try again and let you know.

**Comment by trivita** [comment]
working for me.

**Comment by McSwaggens** [comment]
Works perfectly for me

**Comment by olaulau** [comment]
yes, it works fine. my mistake.
